:heavy_plus_sign: Add 3dCM to required AFNI packages
To resolve / prevent
```
OSError: No command "3dCM" found on host < SHA >. Please check that the corresponding package is installed.
```